import { describe, expect, it } from 'vitest'
import rawFixtures from '../../../../fixtures/lot-sizing.json'
import { wagnerWhitin } from './wagner-whitin'

// Golden fixtures generated by fixtures/generate.py from Python stockpyl
// (`stockpyl.wagner_whitin.wagner_whitin`), whose leading case reproduces
// Snyder & Shen, Fundamentals of Supply Chain Theory 2e, Example 3.9.
// stockpyl charges holding on end-of-period inventory — the same convention as
// cost.ts — so the total cost must agree exactly. Its output lists are
// 1-indexed with a placeholder at element 0; the generator translates them to
// our 0-indexed periods. See that script's module docstring.
interface WagnerWhitinFixture {
  name: string
  demand: number[]
  setupCost: number
  holdingCostPerUnitPerPeriod: number
  expected: {
    orders: { period: number; quantity: number }[]
    totalCost: number
  }
}
const fixtures = rawFixtures as unknown as { wagnerWhitin: WagnerWhitinFixture[] }

// Both implementations solve the same DP exactly in float64 over integer demand;
// anything beyond ~1e-9 would be a real disagreement, not float noise.
const EXACT = 9

describe('golden: stockpyl wagner_whitin', () => {
  it.each(fixtures.wagnerWhitin)('matches stockpyl on $name', (f) => {
    const result = wagnerWhitin(f.demand, {
      setupCost: f.setupCost,
      holdingCostPerUnitPerPeriod: f.holdingCostPerUnitPerPeriod,
    })
    expect(result.value.orders).toEqual(f.expected.orders)
    expect(result.value.totalCost).toBeCloseTo(f.expected.totalCost, EXACT)
  })

  it('decomposes FoSCT Example 3.9 into the documented setup/holding split', () => {
    // The fixture pins only stockpyl's total (1380). This pins OUR decomposition
    // of it, which is what proves the holding convention matches rather than two
    // errors cancelling: setup 2×500 = 1000; holding 2·(1·120) + 2·(1·70) = 380.
    const result = wagnerWhitin([90, 120, 80, 70], {
      setupCost: 500,
      holdingCostPerUnitPerPeriod: 2,
    })
    expect(result.value.setupCost).toBe(1000)
    expect(result.value.holdingCost).toBe(380)
    expect(result.value.totalCost).toBe(1380)
  })
})
