import { describe, expect, it } from 'vitest'
import rawFixtures from '../../../fixtures/forecasting.json'
import { croston } from './croston'
import { holt } from './holt'
import { holtWinters } from './holt-winters'
import { sba } from './sba'
import { ses } from './ses'
import { tsb } from './tsb'

// Golden fixtures generated by fixtures/generate.py from Python statsforecast
// (Croston/SBA/TSB/SES) and statsmodels with known initial states (Holt/HW).
// See that script's module docstring for why each reference is comparable.
interface PointFixture {
  series: number[]
  alpha: number
  expected: number
}
interface TsbFixture {
  series: number[]
  alphaDemand: number
  alphaProbability: number
  expected: number
}
interface HoltFixture {
  series: number[]
  alpha: number
  beta: number
  phi?: number
  horizon: number
  expected: number[]
}
interface HwFixture {
  series: number[]
  seasonLength: number
  mode: 'additive' | 'multiplicative'
  alpha: number
  beta: number
  gamma: number
  horizon: number
  expected: number[]
  fitted: number[]
}
const fixtures = rawFixtures as unknown as {
  croston: PointFixture[]
  sba: PointFixture[]
  ses: PointFixture[]
  tsb: TsbFixture[]
  holt: HoltFixture[]
  holtWinters: HwFixture[]
}

// Same recursion and initialisation convention in both implementations, both
// in float64 — differences beyond ~1e-9 would mean a real disagreement.
const EXACT = 9

describe('golden: statsforecast CrostonClassic / CrostonSBA', () => {
  it.each(fixtures.croston)('croston matches statsforecast on $series', (f) => {
    expect(croston(f.series, { alpha: f.alpha }).value.forecast[0]).toBeCloseTo(f.expected, EXACT)
  })

  it.each(fixtures.sba)('sba matches statsforecast on $series', (f) => {
    expect(sba(f.series, { alpha: f.alpha }).value.forecast[0]).toBeCloseTo(f.expected, EXACT)
  })
})

describe('golden: statsforecast TSB', () => {
  it.each(
    fixtures.tsb,
  )('tsb(α_z=$alphaDemand, α_p=$alphaProbability) matches statsforecast on $series', (f) => {
    const r = tsb(f.series, { alphaDemand: f.alphaDemand, alphaProbability: f.alphaProbability })
    expect(r.value.forecast[0]).toBeCloseTo(f.expected, EXACT)
  })
})

describe('golden: statsforecast SimpleExponentialSmoothing', () => {
  it.each(fixtures.ses)('ses(α=$alpha) matches statsforecast', (f) => {
    expect(ses(f.series, { alpha: f.alpha }).value.forecast[0]).toBeCloseTo(f.expected, EXACT)
  })
})

describe('golden: statsmodels Holt (known init l=y₀, b=y₁−y₀)', () => {
  it.each(fixtures.holt)('holt(α=$alpha, β=$beta, φ=$phi) matches statsmodels', (f) => {
    const r = holt(f.series, {
      alpha: f.alpha,
      beta: f.beta,
      horizon: f.horizon,
      ...(f.phi !== undefined ? { phi: f.phi, damped: true } : {}),
    })
    // 1e-6: identical recursion, but statsmodels accumulates states in its own
    // order of operations.
    f.expected.forEach((e, h) => {
      expect(r.value.forecast[h]).toBeCloseTo(e, 6)
    })
  })
})

describe('golden: statsmodels Holt-Winters (known heuristic init)', () => {
  it.each(fixtures.holtWinters)('holtWinters($mode, m=$seasonLength) matches statsmodels', (f) => {
    const r = holtWinters(f.series, {
      seasonLength: f.seasonLength,
      mode: f.mode,
      alpha: f.alpha,
      beta: f.beta,
      gamma: f.gamma,
      horizon: f.horizon,
    })
    // Forecasts compared only for h < m: statsmodels uses a one-update-stale
    // seasonal index at h ≡ 0 (mod m), where fpp3 §8.4 (which this code and
    // R's forecast::hw follow) uses the latest seasonal states — see
    // fixtures/generate.py.
    f.expected.forEach((e, h) => {
      expect(r.value.forecast[h]).toBeCloseTo(e, 6)
    })
    // The one-step fitted path pins the full recursion (level, trend, and
    // every seasonal update); ours is NaN over the init season, so compare
    // from t = m.
    for (let t = f.seasonLength; t < f.series.length; t++)
      expect(r.value.fitted[t]).toBeCloseTo(f.fitted[t] as number, 6)
  })
})
